### ISSUE TITLE
variable_assignment/set_command token

### ISSUE THREAD

**Issue by ndonfris** [ram02z/tree-sitter-fish#15]
A token to recognize when a variable has been defined would be 
useful. For reference, tree-sitter-bash contains the variable_assignment token.

An example of fish shell variable assignment:
```fish
set -l some_variable 'hello world'

echo "$some_variable"
```

Similar to the `test_command` naming convention, the
token could be named `set_command`.

**Comment by taekwombo** [comment]
Variable assignment is different in fish than in bash.
- In fish you assign variable by executing a `set` command. Therefore, in my opinion, current tree is correct in terms of `set` command (note on test command below).
- In bash you assign variable by writing down variable assignment expression.

Regarding test command - it was defined as a separate grammar rule because of special syntax in fish `[ <test command arguments> ]`.
And the way it is defined in current grammar is not exactly correct.

I think that instead of this:
```fish
test 0 -eq 1
[ 0 -eq 1 ]
```
https://github.com/ram02z/tree-sitter-fish/blob/84436cf24c2b3176bfbb220922a0fdbd0141e406/grammar.ts#L238-L250

It should look like this:
```fish
[ 0 -eq 1 ]
```
```js
        test_command: $=> seq(
            alias(/\[\s/, '['),
            repeat(field('argument', $._test_expression)),
            ']'
        ),
```

Because if you look at it, `test 1 -eq 0` is just a usual command statement in the eye of a parser.

---

If you need to match `set_command` nodes, there are useful queries in nvim-treesitter https://github.com/nvim-treesitter/nvim-treesitter/blob/965a74f76a2999b81fe3a543fb5e53bf6c84b8b7/queries/fish/highlights.scm#L111

**Comment by ndonfris** [comment]
That was super helpful. Thanks!
