### ISSUE TITLE
Fish parser isn't being automatically enable on .fish files

### ISSUE THREAD

**Issue by PopeRigby** [ram02z/tree-sitter-fish#6]
When I open a `.fish` file, the fish parser isn't automatically enabled. It's automatically enabled for all other file types, and I can set it manually with `:set filetype=fish`.

**Comment by ram02z** [comment]
@PopeRigby Create a file called `fish.vim` in your config under the `ftdetect` directory containing `au! BufRead,BufNewFile *.fish set filetype=fish`. Alternatively you can add that same autocommand to your init.vim

**Comment by PopeRigby** [comment]
Oh, is there a reason that isn't mentioned in the setup guide? Seems a little bit strange it doesn't work out of the box.

**Comment by ram02z** [comment]
The reason most filetypes 'work out of the box' is that vim sources `$VIMRUNTIME/filetype.vim` which has autocommands that are used to detect the filetype based on the file extension. `.fish` unforunately isn't one of them, so we have to create our own autocommand.

**Comment by PopeRigby** [comment]
Oh I see. That probably should be in the setup guide then. Would it just take NeoVim adding fish to that file for it to work correctly?

**Comment by ram02z** [comment]
> 
> 
> Would it just take NeoVim adding fish to that file for it to work correctly?

Yes. Relavant issue for vim https://github.com/vim/vim/issues/820.

**Comment by PopeRigby** [comment]
Thanks. Should there also be an issue for nvim?

**Comment by ahelwer** [comment]
@PopeRigby I am also interested in the answer to this question, seems like nvim-treesitter itself could/should contain Vimscript files in its `ftdetect` runtime directory for all the languages it supports, similar to its queries?

**Comment by krnik** [comment]
I think filetype detectipn should be done via plugin or configuration. Otherwise it would be a double effort on the `nvim-treesitter` side.
As an example https://github.com/dag/vim-fish which contains configuration for most of the features needed to support fish.

**Comment by ahelwer** [comment]
@krnik the user experience would be much improved if all users had to do to get the benefits of a tree-sitter grammar for a language were to run `:TSInstall lang` instead of also having to muck around with filetype identification. The nvim-treesitter project already stores query files for all the languages it supports, and even includes ftdetect files for a couple of its languages. Adding a ftdetect file containing the line `au! BufRead,BufNewFile *.fish set filetype=fish` (and for any other grammar neovim doesn't identify by default) to nvim-treesitter is a very small amount of effort/space relative to the improved convenience for users, imo.

**Comment by krnik** [comment]
Good point about the user experience 👍 I completely agree.

**Comment by ram02z** [comment]
Detection of fish files will be merged into nvim-treesitter with this PR https://github.com/nvim-treesitter/nvim-treesitter/pull/1635
